### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by rjrobinson** [soniah/gosnmp#100]
` Error reading from UDP: read udp 10.0.1.4:49582->24.34.214.79:161: i/o timeout `

Seems that I can only get this error, but when using the command line, or the ruby snmp gem, it works fine. 

Any thoughts?

**Comment by hh-h** [comment]
I have the save issue with a few switches:
console snmpbulkwalk ok, 0.2s
console snmpwalk ok, 0.8s
python netsnmp ok, 0.2s
gosnmp timeout

GoSNMP config
```
Version:   gosnmp.Version2c,
Timeout:   time.Duration(6) * time.Second,
Retries:   3,
```

I'll investigate on weekend my issue

**Comment by hh-h** [comment]
Okay, seems like I've figured out the problem. When I started to diff two packets from python library and go library I've noticed that max-repetitions is different.
So when I changed `MaxRepetitions` to lower value (16) problem disappeared.
```
$ snmpbulkwalk -v2c -Cr50 -c public 10.128.4.34 .1.3.6.1.2.1.2.2.1.3
Timeout: No Response from 10.128.4.34
$ snmpbulkwalk -v2c -Cr16 -c public 10.128.4.34 .1.3.6.1.2.1.2.2.1.3
iso.3.6.1.2.1.2.2.1.3.1 = INTEGER: 24
... skipped ...
```
Try to set `MaxRepetitions` to lower value, I'd recommend 10, because it's `snmpbulkwalk` default, but net-snmp's python bindings using 16 and I don't have problems with it.

ex
```
    s := &gosnmp.GoSNMP{
        Target:    ip,
        Port:      uint16(161),
        Community: "public",
        Version:   gosnmp.Version2c,
        Timeout:   time.Duration(6) * time.Second,
        Retries:   2,
        MaxRepetitions: 16,
    }
    err = s.Connect()
```

Cheers

**Comment by soniah** [comment]
Thanks @hh-h @rjrobinson I've updated the comments around MaxRepetitions to reference this issue.

**Comment by marcotollini** [comment]
Thanks a lot!
With this message I hope to help the next person that is doing Walk with goSNMP on Huawei VRP (NE40E): set MaxRepetition at 20, or you will get a Timeout error.
