### ISSUE TITLE
SNMP Traps to accept a context for cancellation / timeouts

### ISSUE THREAD

**Issue by nathanIL** [soniah/gosnmp#124]
Hi,

Currently, there is no sane way to programmatically stop / cancel the listening server (infinite loop).
It should accepts a context to allow cancellations or timeouts.

Thanks,

**Comment by soniah** [comment]
Thanks Nathan, you're right. However I believe channels are a better way of implementing this, so that gosnmp can provide the mechanism and the end user (library user) can implement their policy.

For example one user may want to exit at exactly 9pm, another user after running for 10 seconds, a third if no packets are received for 3 seconds.

Here's an example [using two channels](https://medium.com/@matryer/stopping-goroutines-golang-1bf28799c1cb) (stop and stopped). And here's an explanation of [separation of mechanism and policy](https://en.wikipedia.org/wiki/Separation_of_mechanism_and_policy) for the big picture.

It sounds like you're working with this at the moment, so you could test this properly. Would you mind implementing it and submitting a PR? ;-)

Out of interest, it sounds like you're writing a daemon. I would write this by having my program [listen for standard signals](http://meinit.nl/the-3-most-important-kill-signals-on-the-linux-unix-command-line) eg SIGHUP. And using [supervisord](http://supervisord.org/) or similar to run the program as a daemon.

Thanks, Sonia.

**Comment by soniah** [comment]
Actually, I haven't read this section of code for a while.... Doesn't the following solve your problem?

`func (t *TrapListener) Close() { `

You would then provide the above policies, and send a Close() when ready.
