### ISSUE TITLE
gosnmp.Connect() return not nil even with remote snmpd daemon stoped 

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#65]
Hi @soniah . I'm building some improvements in mi snmpcollector, I would like detect when snmp device is offline to try do periodic re-connections.

When doing the first connection it returns non nil value , but my snmpd daemon is stopped

https://github.com/toni-moreno/snmpcollector/blob/master/pkg/snmp.go#L172

After when trying to do a bulkwalk the client detects errors.
```
INFO[0000] First SNMP connection to host  hostsnmpv3b stablished  <--here first gosnmp.Connect()
INFO[0000] Filter not found for measurement:i linux_cpu 
INFO[0000] Loading Indexed values in : linux_ports      
FATA[0000] SNMP bulkwalk error Error reading from UDP: read udp 127.0.0.1:55412->127.0.0.1:161: read: connection refused 
```

Can you review if I'm doing something wrong ?

Thank you very much

**Comment by soniah** [comment]
I'm overseas at the moment, can I
look it later?

**Comment by toni-moreno** [comment]
yes of course! thank you !!

**Comment by phemmer** [comment]
This is expected. Because UDP is a connectionless protocol, there's no actual connection created. The `Connect()` method simply creates and opens the socket. Until something is sent across it, you don't know that the remote host is there and responding.
Even if you were able to detect that the remote host is there on `Connect()`, it could go away by the time you sent something. And it could also come back again at any time.

**Comment by schotlandzegtja** [comment]
@phemmer is correct. UDP is stateless, so unless you build your own 'connection' construct on top of it, all you get when you 'Connect()' is a listening socket where you can send data and where you can try and receive data.

What I suspect you would want to do is attempt to poll the device; if it returns an error or a value, then you can consider it online.

I'd suggest this issue is closed.

**Comment by soniah** [comment]
Closed - see comments about UDP being stateless. Thank you @toni-moreno @phemmer @schotlandzegtja for your request and comments :-)

**Comment by toni-moreno** [comment]
Hi @phemmer and @soniah IMHO if we are working only with a connectionless protocol the gonsmp.Connect() is not a good API Method name, could be better something like gosnmp.PrepareProtocol() 

When I did the first Connect() I expect the method can do something in the server side to give me an idea that server side is ok.

IMHO the documentation also give us an erroneous idea on what this method does.
 
https://godoc.org/github.com/soniah/gosnmp#GoSNMP.Connect

What do you think about?

**Comment by soniah** [comment]
Thank you Toni. I've updated the documentation:

_Connect creates and opens a socket. Because UDP is a connectionless protocol, you won't know if the remote host is responding until you send packets. And if the host is regularly disappearing and reappearing, you won't know if you've only done a Connect()._

_For historical reasons (ie this is part of the public API), the method won't be renamed._
